service: aws-lambda-mongodb

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 8
  stage: default
  region: ap-south-1


functions:
  api: 
    handler: lambda.handler
    events:
      - http: ANY /{proxy+}  
      - http: ANY /


    

